nohup: ignoring input
[[1 2 3]
 [4 5 6]]
Supervised Training started
heuristic: min_degree actor learning rate: 0.001 epochs: 500 DataSet: UFSMDataset_Demo

| Xavier Initialization
| Xavier Initialization
Use Critic:
False
/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/gcn/models_gcn.py:213: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  features = F.log_softmax(features.t())
parameter name actor.gc1.weight parameter value tensor(1.00000e-02 *
       [[ 1.7804]], device='cuda:0')
parameter name actor.gc1.bias parameter value tensor(1.00000e-02 *
       [[-1.3048]], device='cuda:0')
parameter name actor.gc2.weight parameter value tensor(1.00000e-03 *
       [[ 7.4140]], device='cuda:0')
parameter name actor.gc2.a parameter value tensor([[ 0.2317],
        [ 0.6710]], device='cuda:0')
parameter name actor.gc2.bias parameter value tensor(1.00000e-02 *
       [[ 1.7918]], device='cuda:0')
/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/rl/train_a2c_mc.py:531: RuntimeWarning: invalid value encountered in double_scalars
  _val_ave_gcn = np.sum(val_gcn_greedy) / len(val_gcn_greedy)
/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/rl/train_a2c_mc.py:537: RuntimeWarning: invalid value encountered in double_scalars
  _val_ave_mind = np.sum(val_mind) / len(val_mind)
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCThrustAllocator.cuh line=21 error=2 : out of memory
Traceback (most recent call last):
  File "main_mc.py", line 213, in <module>
    density = args.p
  File "/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/rl/train_a2c_mc.py", line 367, in train_and_validate
    action, log_prob, reward, value_current, value_next, x_model = self.model(x_model) # forward propagation,action: node selected, reward: nb edges added
  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-5.2.0/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/rl/model_a2c.py", line 150, in forward
    probs = self.actor(features, adj_M)  # call actor to get a selection distribution
  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-5.2.0/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/gcn/models_gcn.py", line 212, in forward
    features = self.gc2(features, adj_matrix)
  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-5.2.0/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/local_workspace/liudefen/PycharmProjects/PycharmProjects/GraphRL/gcn/layers_gcn.py", line 332, in forward
    features = torch.spmm(atten_sparse, features)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCThrustAllocator.cuh:21
